### ISSUE TITLE
Filter by category fails to show available categories

### ISSUE THREAD

**Issue by servilla** [PASTAplus/dex#1]
When processing `https://dex.edirepository.org/https%3A%2F%2Fpasta-d.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-ble%2F17%2F5%2Fa43ae92c34e99b8b03a0ff28b08a916a`, the subse/filter_by_category does not show categories even though column label shows three categories:

![image](https://user-images.githubusercontent.com/2224723/102301679-864cad80-3f14-11eb-8556-ca6fd6255572.png)

**Comment by rogerdahl** [comment]
Fixed. "Click to select" will now show when a column has been selected while no categories have been selected.
