### ISSUE TITLE
Profile fails to load with 504 Gateway Time-out

### ISSUE THREAD

**Issue by servilla** [PASTAplus/dex#2]
When attempting to load the profile for `https://dex.edirepository.org/https%3A%2F%2Fpasta-d.lternet.edu%2Fpackage%2Fdata%2Feml%2Fknb-lter-ble%2F17%2F5%2Fa43ae92c34e99b8b03a0ff28b08a916a`, the result is a 504 Gateway Time-out even though there are only 45 rows in this CSV file.

**Comment by rogerdahl** [comment]
Resolved by removing the Interactions plots (this CSV caused ~700 plots to be generated).
