### ISSUE TITLE
Dex fails to load for entity in ver 2 of staged data package

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/dex#38]
I get the 502 bad gateway message when I try to access Dex from the link in the resources section of this ver 2 package in the staging environment (only the first table, which was changed from ver1 of the staged package, fails to open.) There were no problems opening it from the ver 1 package. Date and time columns were reformatted between versions, and missing value codes + explanations were added to the metadata.

package: https://portal-s.edirepository.org/nis/mapbrowse?scope=edi&identifier=748
problematic entity: https://pasta-s.lternet.edu/package/data/eml/edi/748/2/e7209e56ec3548d0f5e5b7d4939018de

Notes:

I tried putting the package in portal-d and it still doesnt work.
I try loading the table from dex.edirepository.org using the entity url and it still doesnt work

**Comment by servilla** [comment]
@kzollove the root cause of this problem was a legacy database constraint on the entity hash value, which is no longer necessary. The constraint has been removed and that entity does now load into DeX. Sorry for the inconvenience.

**Comment by kzollove** [comment]
thanks for the quick fix @servilla
