### ISSUE TITLE
Large CSV tables result in "Out of Memory" exceptions on server

### ISSUE THREAD

**Issue by servilla** [PASTAplus/dex#40]
Large CSV tables result in "Out of Memory" exceptions on the server. Specifically, [this table in DeX](https://dex.edirepository.org/dex/profile/26) loads into Pandas Profile, Subset, but results in an exception when attempting to view the plot.

The corresponding data package in the EDI Data Portal (staging) is: https://portal-s.edirepository.org/nis/mapbrowse?packageid=edi.143.11

**Comment by rogerdahl** [comment]
We've added a limit to the number of rows that can be processed in a single CSV to prevent out of memory exceptions. Now set to 1m. Can be adjusted as needed.

**Comment by rogerdahl** [comment]
Current limit works on number of cells and is set to 50m.
