### ISSUE TITLE
Provide an API to enable ezEML to fire up DeX on a particular data table

### ISSUE THREAD

**Issue by jon-ide** [PASTAplus/dex#74]
Provide an API to enable ezEML to fire up DeX on a particular data table.

ezEML has a Check Data Tables page where individual tables in a package are displayed with links to check the table. It would be awesome to also have a link/button for each table to Explore the Data that would open DeX on the table in a new tab.

**Comment by rogerdahl** [comment]
DeX will expose an interface where links to EML and CSV elements can be submitted for opening in a browser. Since these objects are works in progress, we'll want to clear caches for them if resubmitted.

**Comment by servilla** [comment]
...or don't cache at all if the referrer is ezEML.

**Comment by jon-ide** [comment]
ezEML caches the results of Check Data Table and clears the cached results for a table when the table's metadata changes or the table is re-uploaded. I.e., ezEML keeps track of whether the cached results can be trusted. So, ezEML could, in its call to the DeX API, indicate whether DeX can use a previously cached result if it has one.
