### ISSUE TITLE
The dex-cache requires some means of garbage collection

### ISSUE THREAD

**Issue by servilla** [PASTAplus/dex#76]
The production dex server returned a 500 internal server error on 2024-05-26 due to an out-of-disk memory error. For this reason, dex will require some type of garbage collection to run either regularly or on detection of low disk space to clean out the dex-cache directory.

**Comment by servilla** [comment]
Garbage collection should also include the /tmp/dex-tmp-cache, which is also space-consuming.

**Comment by jwbrunt** [comment]
Deployed and tested servilla script /home/pasta/dex/gc.sh from dex-d on dex. Operating from cron at midnight UTC. Monitoring /home/pasta/dex/gc.log for proper performance.
